version: '3.1'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 5233:5233
        depends_on:
            - db
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: example